[package]
name = "kami"
#author = "mrfluffy-dev"
license = "GPL-3.0"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.6"
colored = "2.0.0"
isahc = "1.7.2"
base64 = "0.13"
